# The Site Configuration

# Basics
title: zhanbin.com
tagline: 詹膑个人站存档
description: >-
  zhanbin.com 詹膑（horse）的个人站 2005-2012 存档
url: "https://ofpix.github.io/zhanbin-com"
baseurl: "/zhanbin-com"

# Theme
theme: jekyll-theme-chirpy

# Language
lang: zh-CN
timezone: Asia/Shanghai

# Author
author: 詹膑

# Build
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - tools
  - .devcontainer
  - .vscode

# Social
social:
  name: 詹膑

# Archives
jekyll-archives:
  enabled: [categories, tags, year, month]
  layouts:
    year: year
    month: month
  permalinks:
    year: /archives/:year/
    month: /archives/:year/:month/
